version: '3.7'
services:
  mongo:
    image: mongo
    volumes:
      - db-data:/data/db
  backend:
    build: backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  frontend:
    build: frontend
    ports:
      - "3000:80"
    depends_on:
     - backend

volumes:
  db-data:
